name: run api.py

on:
  schedule:
    - cron: '*/5 * * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: execute py script # run main.py
        run:  api.py
          
      
          
      
